### ISSUE TITLE
Is there way to use custom primitives?

### ISSUE THREAD

**Issue by ArcanisCz** [open-source-labs/ReacType#123]
I think this tool cannot become really usefull, if there is no way to add custom primitives. I cannot build application from just provided Button/List/Paragraph/... 
I would like to create app from, lets say,  https://react.semantic-ui.com/ . Is there a way?

**Comment by ChristianEdwardPadilla** [comment]
Which primitives are most important to add, in your opinion? Custom components can be added alongside vanilla HTML elements currently. Still in active development, so we're taking any suggestions (and pull requests, of course). Thanks!

**Comment by ArcanisCz** [comment]
>  Custom components can be added alongside vanilla HTML elements currently.

Where? I see only Image, Form, Button, Link, List and Paragraph in my pallete.

Usecase on my mind is this: 

I have component library (private, or premade like react-bootstrap) and use this tool to prototype application from our component. I imagine clicking some import button somehow, then every component from component library appears in the palette ready to use.

If this tool is intended for prototyping, its important to lower barrier to start prototyping. So adding components individually for each started prototype project would be a bit painful.

**Comment by jguffey** [comment]
This app looks great but the first question I had is the same as @ArcanisCz.

This app would be extremely useful if you could inject custom components from component libraries such as [Material IU](https://material-ui.com/), [IBM Carbon](https://www.carbondesignsystem.com/developing/frameworks/react/), or even custom proprietary UI libraries like the one I use at my job. 

After browsing the source code for a short time, it looks like [this](https://github.com/open-source-labs/ReacType/blob/53ededfe67e84835e92f6bf46e7d11c91edd792d/app/src/context/HTMLTypes.tsx#L12) might be the best place to load and inject those components. If I have time I'll give that a try and report back my findings.

It might also be useful to think about a process to include these custom UI libraries in a way that's easier than injecting into the source code. If I come up with any ideas I will post back here.
