### ISSUE TITLE
Is there way to group components into folders?

### ISSUE THREAD

**Issue by ArcanisCz** [open-source-labs/ReacType#124]
If this tools is to be used for any serious project, it needs ability to somehow group components together (into something similar to folders). Each serious use would mean non-trivial amount of components, which cannot be structuren in single flat list.

**Comment by ChristianEdwardPadilla** [comment]
At the moment all exported components are grouped into a Components folder (within src if exported with config files). Folder structure customization is absolutely on the list of todo features. Thanks for the suggestion!

**Comment by ArcanisCz** [comment]
When #123 and #124 are there, i think i can start to use this out of the box immediately :) awesome work btw!
