### ISSUE TITLE
How to open an image file in ReacType

### ISSUE THREAD

**Issue by xiaoleATRI** [open-source-labs/ReacType#127]
In your README, I notice that you can put an image file (maybe it's a sketch file) in App root component. I tried File -> Open File to open a jpeg file in my mac and it didn't work.

Could you show me how to open an image file in ReacType?

**Comment by tolgamizrakci** [comment]
hello @xiaoleATRI. you can add an image by creating an html image element from the left bottom panel. after creating the element, you can click on the "html attributes" tab (while that img element is selected) and add the image url and save it. the image url could be from the web or the directory of an image in your local files. make sure to include the extension at the end. (ie. .png) I believe ReacType only supports pngs at the moment, but are improving the image features at the moment.

**Comment by JulioCVaz** [comment]
Hi.

When I add a new element ** Src ** in ** img ** The text display is in CamelCase. Example: Src = {HttpsGithubComJulioCVazSomDeGaragemBlobMasterReferenciaJpg}, how to use without CamelCase?

**Comment by JulioCVaz** [comment]
Hi.

When I add a new element **Src** in **img** The text display is in CamelCase. Example: Src = {HttpsGithubComJulioCVazSomDeGaragemBlobMasterReferenciaJpg}, how to use without CamelCase?

**Comment by tolgamizrakci** [comment]
Hi Julio:) are you talking about the 'img' field inside the 'HTML Attributes' Tab?

**Comment by JulioCVaz** [comment]
Yes! That's it!

I must have done something wrong, I'm exploring the tool hahaha !!! But I believe I will!

Thank you!  :thumbsup:

**Comment by JulioCVaz** [comment]
I try in Ubuntu/Linux.

Now I will try on windows to see the result.
