### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by JulioCVaz** [open-source-labs/ReacType#132]
Create Tutorial - Getting Started

Hello, I believe in the potential of the tool, I would like to help with the project in the documentation and create a brief use tutorial :smile:

**Comment by tolgamizrakci** [comment]
We're working on creating a video tutorial actually. If you have any ideas we would be happy to see them:) Until then, we'll try to improve the gifs in the readme.

**Comment by JulioCVaz** [comment]
Ok! thank you! I'll try to help :)
