### ISSUE TITLE
cloneDeep being used more than necessary in reducers

### ISSUE THREAD

**Issue by ChristianEdwardPadilla** [open-source-labs/ReacType#147]
see: https://twitter.com/dan_abramov/status/688087202312491008?lang=en

**Comment by tonyito** [comment]
Hi, Christian. I'm from LA Cohort 34. My team is currently iterating on this application right now and plan to resolve this issue by the time we merge our branch into this repo in a couple of weeks.

Thanks,

Tony

**Comment by ChristianEdwardPadilla** [comment]
Hey Tony
Happy to talk with the group. I can run you thru some of the parts of the code. Maybe give some suggestions for what to work on.

contact: christianepadilla@gmail.com
