### ISSUE TITLE
Unable to edit components

### ISSUE THREAD

**Issue by cuginoAle** [open-source-labs/ReacType#157]
Hi there,
thanks for building this tool, it looks very promising!
I installed it (the electron app, OSX) and I started using it but I am failing to figure out how to edit a component. I.e. I can only add Divs, Images, Headers but I don't know how to set attributes/props/content.
I.e. how do I set an image src or a button onClick function?

thanks and keep up with the good work!

**Comment by andrewjcho84** [comment]
Hey cuginoAle,

Thanks for downloading and testing out our app! Sorry the functionality you want isn't there yet. We designed the app to be basic generation so it only includes attributes like display, size (width, height), and background color. Specific attributes like image source or event listeners are not implemented. We wanted to just build that foundation or skeleton structure of the user's next project and then the user can build off that generated code in their own IDE to add their own customizations.

**Comment by cuginoAle** [comment]
Oh I see,
thanks for clarifying this!
It would be great if we could "edit" those components (either using ReacType itself or importing components built using an external IDE)... it would be like Storybook... but much more powerful as it will not only be useful for documenting and presenting components, but it would be a tool to compose and generate fully functioning pages/apps as well.
I'll keep an eye on this project ;)

cheers!
