### ISSUE TITLE
cant run ReacType.exe Error modal shown ffmpeg.dll not found

### ISSUE THREAD

**Issue by Sensiblemnd** [open-source-labs/ReacType#162]
Download from ReacType.exe  
https://github.com/open-source-labs/ReacType/releases/tag/Windows.5.0.0

Double click to run

Error
ReactType.exe - system Error
The code execution cannot proceed because ffmpeg.dll not found. Reinstalling the program may fix the problem

Os Windows 10 64 bit

**Comment by aw2934** [comment]
Hello Sensiblemnd,

Thank you for downloading our app and notifying us of this issue. We've looked into it, and we think it should be resolved in the newly uploaded Windows installer. Please let us know if the issue persists.

**Comment by waynebrantley** [comment]
still happens with 6.0

**Comment by mhs-mlkn** [comment]
I had the same problem with the version 6.0. I downloaded ffmpeg.dll from internet and copy it to system folder and try again now the error massage has changed and I get this error:
The procedure entry point av_buffer_create could not be located in the dynamic link library

**Comment by neocris** [comment]
maybe repack this as an electronjs app which comes with ffmpeg bundled
