### ISSUE TITLE
Cannot Sign-up Password not valid

### ISSUE THREAD

**Issue by anthonycmain** [open-source-labs/ReacType#165]
I'm trying to sign up using the Mac app 5.0 but cant create account I just get non-valid password warning.

Try using the following password to test Test123_!

![Screenshot 2021-02-18 at 14 09 02](https://user-images.githubusercontent.com/950131/108368903-e3096480-71f2-11eb-9686-2664708a9bc5.png)

**Comment by Kappyh** [comment]
Can I take a look at this?
Is not clear if I can contributte on this project.
